/* !file overlay11 */
OpcodeCheck = 0x022DDDD4;
GetParameterCount = 0x022DDD8C;
ScriptEngineReturnTwo = 0x022E246C;

/* !file overlay29 */
ApplyMoveEffect = 0x0232E864;
ApplyMoveEffectHookAddr = 0x0232F8A4;
ApplyMoveEffectJumpAddr = 0x023326CC;
ApplyItemEffectHookAddr = 0x0231B9D8;
ApplyItemEffectJumpAddr = 0x0231CB14;

/* Add your own symbols here... */
RefreshStorage = 0x0201007c;

/* Splash screen */
LoadBackgroundBgp = 0x2052060; /* EU: 0x2052398 */
BGP21C_PTR = 0x20B09B0; /* EU: 0x20B12CC */
TitleCardHookLoad1 = 0x234834C; /* EU: 0x2348F4C */
TitleCardHookLoad2 = 0x2348368; /* EU: 0x2348F68 */
TitleCardHookLoad3 = 0x2348450; /* EU: 0x2349050 */

/* Fade in top screen for floor card */
FloorCardFadeInHook = 0x2348378; /* EU: 0x2348F78 */
FloorCardFadeOutHook = 0x234843C; /* EU: 0x234903C */
FloorCardSaveFloorNumHook = 0x204F704; /* EU: 0x204FA3C */
GetStratumNameStringId = 0x204F74C; /* EU: 0x204FA84 */

/* !file arm9 */
ChangeGlobalBorderColor = 0x02027A80;
UppercaseTextTagFatalError = 0x02021A10;
AfterUppercaseTagIsFound = 0x02021AA0;
GetTextSpeed = 0x02020ED0;
DoTextLoop = 0x02020EE0;
AnalyzeTextReturn = 0x02021EC8;
